/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void blackAndWhite () {
        Bitmap blackAndWhite = new Bitmap("Coffee", "BWImage","Black and White");
        assertEquals("Black and White", blackAndWhite.getResult());
    }

    @Test
    void rotate () {
        Bitmap blackAndWhite = new Bitmap("Coffee", "BWImage","Rotate");
        assertEquals("Rotate", blackAndWhite.getResult());
    }

    @Test
    void border () {
        Bitmap blackAndWhite = new Bitmap("Coffee", "BWImage","Border");
        assertEquals("Border", blackAndWhite.getResult());
    }
}
